# Generated by Django 3.2.5 on 2021-07-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=500)),
                ('DoctorName', models.CharField(max_length=500)),
                ('DateOfAppointment', models.DateField()),
                ('TimeOfAppointment', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('UserRole', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
            ],
        ),
    ]
